[package]
name = "one_arena"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.59.0" }

[addresses]
one_arena = "0x0"
